apiVersion: v1
kind: ConfigMap
metadata:
  name: adservice
data:
  PORT: "9555"
  DISABLE_PROFILER: "1"
  PYTHONUNBUFFERED: "1"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: adservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: adservice
          image: srikanthhg/adservice:v1
          ports:
          - containerPort: 9555
          envFrom:
          - configMapRef:
              name: adservice
          resources:
            requests:
              cpu: 100m
              memory: 220Mi
            limits:
              cpu: 200m
              memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: ClusterIP # by default ClusterIP
  selector:
    app: adservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: 9555 #service-port
    targetPort: 9555 #container-port